<template>
    <MainRow>
        <MainCol>
            <Ticket></Ticket>
        </MainCol>
        <MainSubCol>
            <ActionPanel>
                <ActionItem></ActionItem>
                <ActionItem></ActionItem>
                <ActionItem></ActionItem>
            </ActionPanel>
        </MainSubCol>
    </MainRow>
</template>