<template>
    <VRowMain>
        <VColMain>
            <Ticket></Ticket>
        </VColMain>
        <VColMainSub>
            <ActionPanel>
                <ActionItem></ActionItem>
                <ActionItem></ActionItem>
                <ActionItem></ActionItem>
            </ActionPanel>
        </VColMainSub>
    </VRowMain>
</template>